### ISSUE TITLE
Looking for better favicon

### ISSUE THREAD

**Issue by NilsTheBest** [NilsTheBest/ChairOfRepublic#3]
Currently, it's just a chair on a white background. Would anyone be able to draw a favicon (32x32 icon at the left of the tab) in 32 by 32 pixels? It'd be greatly appreciated, thanks!

**Comment by ezrockofficial** [comment]
Honestly, I think the current favicon you have right now is fine, but I think it should have a transparent background since it looks kinda weird when you're not in the Chair Of Republic tab, at least this is just my thoughts. 

I decided to do a little editing with the photo and here is how it turned out: 
(Big image)
![ikeachairedit](https://user-images.githubusercontent.com/48265281/63390194-d133d080-c373-11e9-9771-e02861909982.png)

(Actual favicon image)
![ikeachairedit](https://user-images.githubusercontent.com/48265281/63390415-a6964780-c374-11e9-8c1f-cd7de7630cb8.png)


There are few issues but the image will be really small, so yeah. This could just be used temporarily (of course, I don't mind at all if you don't use this). 
-EZ-Games

**Comment by NilsTheBest** [comment]
I already had a transparent background logo though, but it didn't look good on the tab and we couldn't really see the favicon well when we weren't on the tab, so I figured I'd stick with this one temporarily.
Thanks for the suggestion though! :D

**Comment by ezrockofficial** [comment]
If you haven't already, maybe share this issue in the forums? You might find some artists in the Requests forum, but idk (sorry if I am just posting suggestions you have already done).

**Comment by NilsTheBest** [comment]
Yeah, that sounds like a better idea, I haven't thought of that yet. I know a few people on discord who might be able to help though, I'll see if they can do anything. Thanks!

**Comment by AfterNetwork** [comment]
I could create one, but I can only do 40x40 pixels.

**Comment by AfterNetwork** [comment]
here is it
![Chair of republic](https://user-images.githubusercontent.com/45772308/63644026-26cded00-c694-11e9-95f8-251264a3e99a.png)

**Comment by AfterNetwork** [comment]
or if you want smaller sizes:
[CoRIcons.zip](https://github.com/NilsTheBest/ChairOfRepublic/files/3537685/CoRIcons.zip)

**Comment by NilsTheBest** [comment]
> here is it
> ![Chair of republic](https://user-images.githubusercontent.com/45772308/63644026-26cded00-c694-11e9-95f8-251264a3e99a.png)

Looks great! Could you make the text and chair logo on the icon a bit bigger or just use "CoR" with the chair? It has to fit in a 32 x 32 space :P

**Comment by ajsya** [comment]
I remixed the current studio thumbnail. 
![download](https://user-images.githubusercontent.com/52182942/66174298-56243200-e622-11e9-82f5-3ad6715e58c9.png)

**Comment by ajsya** [comment]
Hmm, I don't know if I like it on the website. What do you think?

**Comment by NilsTheBest** [comment]
Great! This is how it will look like on the website though:
![favtest(1)](https://user-images.githubusercontent.com/41824646/66673531-103e1e00-ec61-11e9-858b-9c8272c17657.png)
I'll try centering it and making "CoR" bigger ^^

**Comment by NilsTheBest** [comment]
![cor-favicon-test](https://user-images.githubusercontent.com/41824646/66674248-bfc7c000-ec62-11e9-8921-72cec7f235bc.png)
I tried this, but the cookies in the background are hardly visible :/

**Comment by ajsya** [comment]
![Screenshot 2019-10-11 at 15 57 55](https://user-images.githubusercontent.com/52182942/66681069-ef190580-ec3f-11e9-9401-9f1008e553da.png)
